import type { Product, Category, Brand } from './types';
import { PlaceHolderImages } from './placeholder-images';

const findImage = (id: string) => {
  const image = PlaceHolderImages.find((img) => img.id === id);
  if (!image) {
    // Fallback to a default image if a specific one isn't found
    const defaultImg = PlaceHolderImages.find((img) => img.id === 'swiss-category');
    if (defaultImg) return defaultImg;
    throw new Error(`Image with id "${id}" not found.`);
  }
  return image;
};

export const products: Product[] = [
  // Rolex
  {
    id: '1',
    name: 'Rolex Submariner',
    slug: 'rolex-submariner',
    category: 'Swiss',
    description: 'Iconic dive watch, waterproof up to 300m.',
    longDescription: 'The Rolex Submariner is the quintessential divers\' watch, a symbol of underwater exploration. It features a robust and functional design with a unidirectional rotatable bezel and solid-link Oyster bracelet.',
    price: 950,
    image: findImage('rolex'),
    isTrending: true,
    brand: 'Rolex',
    modelType: 'Professional',
  },
  {
    id: '13',
    name: 'Rolex Cosmograph Daytona',
    slug: 'rolex-cosmograph-daytona',
    category: 'Swiss',
    description: 'Chronograph for racing drivers, a true icon.',
    longDescription: 'The Cosmograph Daytona is inextricably linked to the world of motor racing. It allows drivers to measure elapsed time and read average speeds on its trademark tachymetric bezel.',
    price: 1000,
    image: findImage('rolex'),
    isTrending: true,
    brand: 'Rolex',
    modelType: 'Professional',
  },
  {
    id: '12',
    name: 'Rolex GMT-Master II',
    slug: 'rolex-gmt-master-ii',
    category: 'Swiss',
    description: 'Dual time-zone watch for pilots and travelers.',
    longDescription: 'Designed to show the time in two different time zones simultaneously, the GMT-Master has been the watch of choice for airline pilots and globetrotters.',
    price: 970,
    image: findImage('rolex'),
    isTrending: false,
    brand: 'Rolex',
    modelType: 'Professional',
  },
  {
    id: '18',
    name: 'Rolex Datejust',
    slug: 'rolex-datejust',
    category: 'Swiss',
    description: 'Timeless design with a classic date display.',
    longDescription: 'The Datejust is the archetype of the classic watch thanks to functions and aesthetics that never go out of style. Launched in 1945, it was the first self-winding waterproof chronometer wristwatch to display the date.',
    price: 880,
    image: findImage('rolex'),
    isTrending: true,
    brand: 'Rolex',
    modelType: 'Classic',
  },
  {
    id: '19',
    name: 'Rolex Day-Date',
    slug: 'rolex-day-date',
    category: 'Swiss',
    description: 'Luxury watch displaying day and date, worn by leaders.',
    longDescription: 'The Rolex Day-Date, often called the "President," is one of the world\'s most prestigious and recognizable watches. It was the first wristwatch to display the day of the week spelled out in full.',
    price: 1000,
    image: findImage('rolex'),
    isTrending: true,
    brand: 'Rolex',
    modelType: 'Classic',
  },
  {
    id: '16',
    name: 'Rolex Yacht-Master',
    slug: 'rolex-yacht-master',
    category: 'Swiss',
    description: 'Nautical watch with regatta timer functionality.',
    longDescription: 'The Yacht-Master is the watch of the open seas. It embodies the spirit of the sailor and is distinguished by its bidirectional rotatable 60-minute graduated bezel.',
    price: 920,
    image: findImage('rolex'),
    isTrending: false,
    brand: 'Rolex',
    modelType: 'Professional',
  },
   {
    id: '17',
    name: 'Rolex Sky-Dweller',
    slug: 'rolex-sky-dweller',
    category: 'Swiss',
    description: 'Complex model with dual time zones and annual calendar.',
    longDescription: 'An elegant watch for world travellers, the Sky-Dweller features an innovative annual calendar and a dual time zone display, all controlled by its revolutionary Ring Command bezel.',
    price: 990,
    image: findImage('rolex'),
    isTrending: false,
    brand: 'Rolex',
    modelType: 'Professional',
  },
  {
    id: '21',
    name: 'Rolex Oyster Perpetual',
    slug: 'rolex-oyster-perpetual',
    category: 'Swiss',
    description: 'The purest Rolex design, simple and versatile.',
    longDescription: 'The Oyster Perpetual is the direct descendant of the original Oyster, the world’s first waterproof wristwatch, on which Rolex has built its reputation since 1926. It is a symbol of universal and classic style.',
    price: 750,
    image: findImage('rolex'),
    isTrending: false,
    brand: 'Rolex',
    modelType: 'Classic',
  },
  {
    id: '14',
    name: 'Rolex Explorer',
    slug: 'rolex-explorer',
    category: 'Swiss',
    description: 'Rugged watch built for adventurers and mountaineers.',
    longDescription: 'The Explorer models are designed for optimal legibility even in the dark, a crucial feature for explorers. They are built to withstand the toughest conditions.',
    price: 850,
    image: findImage('rolex'),
    isTrending: false,
    brand: 'Rolex',
    modelType: 'Professional',
  },
  {
    id: '11',
    name: 'Rolex Sea-Dweller',
    slug: 'rolex-sea-dweller',
    category: 'Swiss',
    description: 'Advanced diving watch with extreme depth resistance.',
    longDescription: 'Rolex\'s ultra-resistant divers\' models engineered for the conquest of the deep. Waterproof to extreme depths, they are the result of decades of collaboration with diving professionals.',
    price: 980,
    image: findImage('rolex'),
    isTrending: false,
    brand: 'Rolex',
    modelType: 'Professional',
  },
  {
    id: '23',
    name: 'Rolex Pepsi',
    slug: 'rolex-pepsi',
    category: 'Swiss',
    description: 'Iconic GMT-Master II with a red and blue bezel.',
    longDescription: 'The "Pepsi" is a nickname for the Rolex GMT-Master II with its iconic red and blue ceramic bezel, reminiscent of the colors of the Pepsi logo. A favorite among collectors.',
    price: 980,
    image: findImage('rolex'),
    isTrending: true,
    brand: 'Rolex',
    modelType: 'Professional',
  },
  {
    id: '24',
    name: 'Rolex Hulk',
    slug: 'rolex-hulk',
    category: 'Swiss',
    description: 'The Submariner with a striking green dial and bezel.',
    longDescription: 'Nicknamed the "Hulk," this version of the Rolex Submariner features a vibrant green dial and a matching green Cerachrom bezel. It\'s a bold and sought-after model.',
    price: 960,
    image: findImage('rolex'),
    isTrending: false,
    brand: 'Rolex',
    modelType: 'Professional',
  },
  {
    id: '25',
    name: 'Rolex Tiffany Daytona',
    slug: 'rolex-tiffany-daytona',
    category: 'Swiss',
    description: 'An ultra-rare Daytona with a Tiffany & Co. blue dial.',
    longDescription: 'A highly coveted and extremely rare version of the Cosmograph Daytona, featuring a dial in the iconic robin\'s-egg blue of Tiffany & Co. A true collector\'s piece.',
    price: 1000,
    image: findImage('rolex'),
    isTrending: true,
    brand: 'Rolex',
    modelType: 'Professional',
  },
  {
    id: '26',
    name: 'Rolex Le Mans Daytona',
    slug: 'rolex-le-mans-daytona',
    category: 'Swiss',
    description: 'A special edition Daytona celebrating the 24 Hours of Le Mans.',
    longDescription: 'This special edition of the Cosmograph Daytona commemorates the 100th anniversary of the 24 Hours of Le Mans race, featuring design elements that pay tribute to the legendary endurance event.',
    price: 1000,
    image: findImage('rolex'),
    isTrending: true,
    brand: 'Rolex',
    modelType: 'Professional',
  },

  // Omega
  {
    id: '2',
    name: 'Omega Seamaster',
    slug: 'omega-seamaster',
    category: 'Swiss',
    description: 'A legacy of deep-sea exploration and innovation.',
    longDescription: 'The Omega Seamaster has a rich maritime heritage. Known for its reliability and style, it has been the watch of choice for adventurers and even James Bond. Its pioneering spirit is evident in every timepiece.',
    price: 750,
    image: findImage('omega'),
    isTrending: true,
    brand: 'Omega',
    modelType: 'Professional'
  },
  {
    id: '27',
    name: 'Omega Speedmaster',
    slug: 'omega-speedmaster',
    category: 'Swiss',
    description: 'The legendary Moonwatch, a staple of space exploration.',
    longDescription: 'The Omega Speedmaster is one of the most iconic watches in the world, famous for being the first watch worn on the Moon. A true chronograph legend.',
    price: 800,
    image: findImage('omega'),
    isTrending: true,
    brand: 'Omega',
    modelType: 'Professional'
  },
  {
    id: '28',
    name: 'Omega Constellation',
    slug: 'omega-constellation',
    category: 'Swiss',
    description: 'Elegant design with iconic claws and star.',
    longDescription: 'The Constellation collection is a symbol of Omega\'s precision and commitment to luxury. It is characterized by its famous "griffes," or claws, and the star emblem on the dial.',
    price: 850,
    image: findImage('omega'),
    isTrending: false,
    brand: 'Omega',
    modelType: 'Classic'
  },
  {
    id: '29',
    name: 'Omega De Ville',
    slug: 'omega-de-ville',
    category: 'Swiss',
    description: 'Classic and sophisticated dress watches.',
    longDescription: 'The Omega De Ville collection represents classic, refined watchmaking. These timepieces are known for their elegant design and the advanced Co-Axial movements within.',
    price: 700,
    image: findImage('omega'),
    isTrending: false,
    brand: 'Omega',
    modelType: 'Classic'
  },
  {
    id: '30',
    name: 'Omega Aqua Terra',
    slug: 'omega-aqua-terra',
    category: 'Swiss',
    description: 'Versatile style for both land and sea.',
    longDescription: 'Part of the Seamaster family, the Aqua Terra is a superb tribute to Omega\'s rich maritime legacy. With a "Teak Concept" dial, it balances sophistication with an ocean spirit.',
    price: 780,
    image: findImage('omega'),
    isTrending: false,
    brand: 'Omega',
    modelType: 'Classic'
  },

  // Patek Philippe
  {
    id: '3',
    name: 'Patek Philippe Nautilus',
    slug: 'patek-philippe-nautilus',
    category: 'Swiss',
    description: 'Unmatched craftsmanship and timeless design.',
    longDescription: 'With the rounded octagonal shape of its bezel, the ingenious porthole construction of its case, and its horizontally embossed dial, the Nautilus has been the epitome of the elegant sports watch since 1976.',
    price: 1000,
    image: findImage('patek-philippe'),
    isTrending: true,
    brand: 'Patek Philippe',
    modelType: 'Classic',
  },
  {
    id: '31',
    name: 'Patek Philippe Calatrava',
    slug: 'patek-philippe-calatrava',
    category: 'Swiss',
    description: 'The quintessential round dress watch.',
    longDescription: 'The Calatrava is the very essence of the round wristwatch and one of the finest symbols of the Patek Philippe style. Supremely elegant, it charms each new generation of watch lovers with its timeless understated perfection.',
    price: 980,
    image: findImage('patek-philippe-calatrava'),
    isTrending: false,
    brand: 'Patek Philippe',
    modelType: 'Classic',
  },
  {
    id: '32',
    name: 'Patek Philippe Aquanaut',
    slug: 'patek-philippe-aquanaut',
    category: 'Swiss',
    description: 'Modern, sporty, and chic with a "tropical" strap.',
    longDescription: 'The Aquanaut, launched in 1997, caused a sensation with its modern, chic design. Its case is a rounded octagon, inspired by that of the Nautilus, and it features a "Tropical" strap made of a new composite material ultra-resistant to wear.',
    price: 950,
    image: findImage('patek-philippe'),
    isTrending: false,
    brand: 'Patek Philippe',
    modelType: 'Classic',
  },
   {
    id: '33',
    name: 'Patek Philippe Complications',
    slug: 'patek-philippe-complications',
    category: 'Swiss',
    description: 'Showcasing horological artistry and useful functions.',
    longDescription: 'Patek Philippe has distinguished itself by its mastery of the so-called "useful" complications, such as annual calendars, dual time zones, and World Time displays, which are immensely practical in everyday use.',
    price: 1000,
    image: findImage('patek-philippe-calatrava'),
    isTrending: false,
    brand: 'Patek Philippe',
    modelType: 'Classic',
  },
   {
    id: '34',
    name: 'Patek Philippe Grand Complications',
    slug: 'patek-philippe-grand-complications',
    category: 'Swiss',
    description: 'The pinnacle of watchmaking mastery.',
    longDescription: 'The Grand Complications collection is the supreme test of a watchmaker\'s skill. Patek Philippe has been a leader in this field for over a century, producing some of the most complex and valuable timepieces in the world.',
    price: 1000,
    image: findImage('patek-philippe'),
    isTrending: true,
    brand: 'Patek Philippe',
    modelType: 'Classic',
  },
  {
    id: '35',
    name: 'Patek Philippe Twenty~4',
    slug: 'patek-philippe-twenty-4',
    category: 'Swiss',
    description: 'A feminine icon for the modern, active woman.',
    longDescription: 'The Twenty~4 was created to accompany the life of the modern, active woman. It is the perfect complement to fashionable business or casual wear and the most elegant evening gowns.',
    price: 900,
    image: findImage('patek-philippe-calatrava'),
    isTrending: false,
    brand: 'Patek Philippe',
    modelType: 'Classic',
  },

  // Tag Heuer
  {
    id: '4',
    name: 'Tag Heuer Carrera',
    slug: 'tag-heuer-carrera',
    category: 'Swiss',
    description: 'Avant-garde watchmaking inspired by motorsport.',
    longDescription: 'Since 1860, TAG Heuer has been at the forefront of Swiss watchmaking, pushing boundaries with its relentless pursuit of innovation, high performance, and precision timing. The Carrera is a racing icon.',
    price: 600,
    image: findImage('tag-heuer'),
    isTrending: true,
    brand: 'Tag Heuer',
    modelType: 'Professional',
  },
  {
    id: '36',
    name: 'Tag Heuer Monaco',
    slug: 'tag-heuer-monaco',
    category: 'Swiss',
    description: 'The iconic square-cased chronograph.',
    longDescription: 'The TAG Heuer Monaco, with its distinctive square case, was a revolutionary watch when it launched in 1969. Worn by Steve McQueen, it\'s a timeless icon of cool.',
    price: 650,
    image: findImage('tag-heuer'),
    isTrending: false,
    brand: 'Tag Heuer',
    modelType: 'Professional',
  },
  {
    id: '37',
    name: 'Tag Heuer Formula 1',
    slug: 'tag-heuer-formula-1',
    category: 'Swiss',
    description: 'For a life in the fast lane, inspired by F1 teams.',
    longDescription: 'The TAG Heuer Formula 1 collection is a casual sports watch for a fast-paced life. The models are made for high performance and are tested to the extreme by the drivers of the Aston Martin Red Bull Racing F1 team.',
    price: 550,
    image: findImage('tag-heuer'),
    isTrending: false,
    brand: 'Tag Heuer',
    modelType: 'Professional',
  },
  {
    id: '38',
    name: 'Tag Heuer Aquaracer',
    slug: 'tag-heuer-aquaracer',
    category: 'Swiss',
    description: 'The ultimate sports watch inspired by the aquatic world.',
    longDescription: 'Reliable in all conditions, the Aquaracer is the essential sports watch. Its robust construction and water-resistance to 300 meters make it the perfect tool for all adventurers.',
    price: 580,
    image: findImage('tag-heuer'),
    isTrending: false,
    brand: 'Tag Heuer',
    modelType: 'Professional',
  },
  {
    id: '39',
    name: 'Tag Heuer Connected',
    slug: 'tag-heuer-connected',
    category: 'Swiss',
    description: 'Swiss luxury watchmaking meets Silicon Valley tech.',
    longDescription: 'The TAG Heuer Connected watch combines the elegance of a chronograph-inspired timepiece with a custom-designed, state-of-the-art digital experience geared towards performance.',
    price: 700,
    image: findImage('tag-heuer'),
    isTrending: false,
    brand: 'Tag Heuer',
  },

  // Seiko
  {
    id: '6',
    name: 'Seiko Prospex',
    slug: 'seiko-prospex',
    category: 'Japanese',
    description: 'Serious watches for serious sports.',
    longDescription: 'Seiko Prospex challenges every limit, with a collection of timepieces for sports lovers and adventure seekers whether in the water, in the sky or on land. Since launching Japan’s first diver’s watch in 1965, Seiko’s innovative technology has changed global standards.',
    price: 500,
    image: findImage('seiko'),
    isTrending: true,
    brand: 'Seiko',
  },
  {
    id: '40',
    name: 'Grand Seiko',
    slug: 'grand-seiko',
    category: 'Japanese',
    description: 'The pinnacle of Japanese precision and craftsmanship.',
    longDescription: 'Grand Seiko represents the pinnacle of Seiko\'s watchmaking, with a focus on precision, durability, and beauty. Each watch is a masterpiece of understated elegance and technical perfection.',
    price: 900,
    image: findImage('seiko'),
    isTrending: false,
    brand: 'Seiko',
  },
  {
    id: '41',
    name: 'Seiko 5',
    slug: 'seiko-5',
    category: 'Japanese',
    description: 'Affordable automatic watches loved for over 50 years.',
    longDescription: 'For over half a century, Seiko 5 Sports has delivered consistently high levels of reliability, durability, performance and value that have endeared it to mechanical watch lovers worldwide.',
    price: 400,
    image: findImage('seiko'),
    isTrending: false,
    brand: 'Seiko',
  },
  {
    id: '42',
    name: 'Seiko Presage',
    slug: 'seiko-presage',
    category: 'Japanese',
    description: 'Combining Japanese aesthetics with traditional craftsmanship.',
    longDescription: 'The Presage collection combines a Japanese aesthetic sense with traditional craftsmanship and Seiko’s mechanical watchmaking skills in an original collection that offers Japanese beauty, quality and long-lasting performance.',
    price: 480,
    image: findImage('seiko'),
    isTrending: false,
    brand: 'Seiko',
  },
  {
    id: '43',
    name: 'Seiko Astron',
    slug: 'seiko-astron',
    category: 'Japanese',
    description: 'The world\'s first GPS solar watch.',
    longDescription: 'By connecting to the GPS network, the Astron adjusts at the touch of a button to your time zone and, by taking all the energy it needs from light alone, never needs a battery change.',
    price: 650,
    image: findImage('seiko'),
    isTrending: false,
    brand: 'Seiko',
  },
  {
    id: '44',
    name: 'Seiko Kinetic',
    slug: 'seiko-kinetic',
    category: 'Japanese',
    description: 'Powered by motion, a revolutionary quartz technology.',
    longDescription: 'Kinetic is a platform that houses Seiko\'s unique technology that converts kinetic energy into electrical energy, making it an environmentally friendly and highly accurate timepiece.',
    price: 420,
    image: findImage('seiko'),
    isTrending: false,
    brand: 'Seiko',
  },
  {
    id: '45',
    name: 'Seiko Turtle',
    slug: 'seiko-turtle',
    category: 'Japanese',
    description: 'A beloved diver\'s watch with a unique cushion case.',
    longDescription: 'Part of the Prospex line, the "Turtle" is named for its cushion-shaped case that resembles a turtle\'s shell. It\'s a robust and reliable diver\'s watch with a dedicated fan base.',
    price: 520,
    image: findImage('seiko'),
    isTrending: false,
    brand: 'Seiko',
  },

  // Casio
  {
    id: '7',
    name: 'Casio G-Shock',
    slug: 'casio-g-shock',
    category: 'Japanese',
    description: 'The ultimate tough watch, built to withstand anything.',
    longDescription: 'G-SHOCK is the watch that brought the new concept of toughness to the watch. It was born from a developer\'s belief that it was possible to construct a watch that would not break, even if dropped.',
    price: 400,
    image: findImage('casio'),
    isTrending: true,
    brand: 'Casio',
  },
  {
    id: '46',
    name: 'Casio Edifice',
    slug: 'casio-edifice',
    category: 'Japanese',
    description: 'High-performance chronographs with a motorsports spirit.',
    longDescription: 'The Edifice collection of watches from Casio blends a dynamic form with an intricately detailed face. Edifice is a leading-edge chronograph that has been advancing the frontiers of timepiece technology.',
    price: 450,
    image: findImage('casio'),
    isTrending: false,
    brand: 'Casio',
  },
  {
    id: '47',
    name: 'Casio ProTrek',
    slug: 'casio-protrek',
    category: 'Japanese',
    description: 'The perfect outdoor companion with advanced sensor tech.',
    longDescription: 'Pro Trek is a line of watches by Casio designed for outdoor enthusiasts. They feature triple sensor technology: compass, thermometer, and barometer/altimeter.',
    price: 480,
    image: findImage('casio'),
    isTrending: false,
    brand: 'Casio',
  },
  {
    id: '48',
    name: 'Casio Oceanus',
    slug: 'casio-oceanus',
    category: 'Japanese',
    description: 'Elegant solar-powered, radio-controlled watches.',
    longDescription: 'Based on the concept of "Elegance, Technology", Oceanus is a solar-powered, radio-controlled watch that combines advanced functionality with a European design in a beautifully finished titanium case.',
    price: 600,
    image: findImage('casio'),
    isTrending: false,
    brand: 'Casio',
  },
  {
    id: '49',
    name: 'Casio Wave Ceptor',
    slug: 'casio-wave-ceptor',
    category: 'Japanese',
    description: 'Perfect timekeeping with radio-controlled accuracy.',
    longDescription: 'Casio Wave Ceptor watches receive time calibration radio signals to ensure the displayed time is always accurate. A practical and reliable choice for everyday wear.',
    price: 410,
    image: findImage('casio'),
    isTrending: false,
    brand: 'Casio',
  },
  {
    id: '50',
    name: 'Casio Sheen',
    slug: 'casio-sheen',
    category: 'Japanese',
    description: 'Elegant and brilliant timepieces for women.',
    longDescription: 'Sheen is a line of analog watches for women from Casio that are "brilliant, smart, and elegant." Designed with sparkling Swarovski® Crystals for a look that is both refined and beautiful.',
    price: 420,
    image: findImage('casio'),
    isTrending: false,
    brand: 'Casio',
  },

  // Fossil
  {
    id: '10',
    name: 'Fossil Grant',
    slug: 'fossil-grant',
    category: 'Other',
    description: 'Classic chronograph with Roman numerals.',
    longDescription: 'The Grant collection is a testament to timeless style. With its classic Roman numerals and chronograph movement, it\'s a watch that is both sophisticated and functional.',
    price: 420,
    image: findImage('fossil'),
    isTrending: false,
    brand: 'Fossil',
  },
  {
    id: '51',
    name: 'Fossil Nate',
    slug: 'fossil-nate',
    category: 'Other',
    description: 'Military-inspired with an oversized, bold look.',
    longDescription: 'With a clean, military-inspired design, the Nate collection has a laid-back yet rugged feel that plays with a subtle sense of masculinity. It\'s an essential for any adventure.',
    price: 430,
    image: findImage('fossil'),
    isTrending: false,
    brand: 'Fossil',
  },
  {
    id: '52',
    name: 'Fossil Caroline',
    slug: 'fossil-caroline',
    category: 'Other',
    description: 'A chic and feminine design for the modern woman.',
    longDescription: 'The Caroline is a beautifully designed timepiece for women, featuring a slim profile and a variety of stunning finishes. It\'s the perfect accessory for both work and weekend.',
    price: 410,
    image: findImage('fossil'),
    isTrending: false,
    brand: 'Fossil',
  },
  {
    id: '53',
    name: 'Fossil Riley',
    slug: 'fossil-riley',
    category: 'Other',
    description: 'A multifunction watch with a touch of sparkle.',
    longDescription: 'The Riley is a versatile and eye-catching multifunction watch. With its crystal-accented bezel and classic dial, it\'s a piece that combines functionality with a bit of glamour.',
    price: 440,
    image: findImage('fossil'),
    isTrending: false,
    brand: 'Fossil',
  },
  {
    id: '54',
    name: 'Fossil Emma',
    slug: 'fossil-emma',
    category: 'Other',
    description: 'Classic and minimalist, perfect for everyday.',
    longDescription: 'The Emma collection is all about simple, clean design. With its minimalist dial and classic strap, it\'s a versatile watch that can be dressed up or down.',
    price: 400,
    image: findImage('fossil'),
    isTrending: false,
    brand: 'Fossil',
  },
   {
    id: '55',
    name: 'Fossil Julian',
    slug: 'fossil-julian',
    category: 'Other',
    description: 'A stylish and unique watch with a distinctive design.',
    longDescription: 'The Julian collection from Fossil features unique design elements that make it stand out. It\'s a great choice for those who want a watch with a bit of personality.',
    price: 450,
    image: findImage('fossil'),
    isTrending: false,
    brand: 'Fossil',
  },
  {
    id: '56',
    name: 'Fossil Archer',
    slug: 'fossil-archer',
    category: 'Other',
    description: 'A refined and modern take on a classic watch.',
    longDescription: 'The Archer collection offers a modern interpretation of classic watch design. With its clean lines and sophisticated details, it\'s a timepiece that exudes confidence.',
    price: 460,
    image: findImage('fossil'),
    isTrending: false,
    brand: 'Fossil',
  },

  // Citizen
  {
    id: '8',
    name: 'Citizen Promaster',
    slug: 'citizen-promaster',
    category: 'Japanese',
    description: 'Professional sports watches for land, sea, and air.',
    longDescription: 'The Promaster series is designed for professionals who challenge their limits. Whether you are a diver, pilot, or mountaineer, Promaster has a watch built for your adventure.',
    price: 450,
    image: findImage('citizen'),
    isTrending: true,
    brand: 'Citizen',
  },
  {
    id: '57',
    name: 'Citizen Eco-Drive',
    slug: 'citizen-eco-drive',
    category: 'Japanese',
    description: 'Powered by any light, never needs a battery.',
    longDescription: 'Citizen\'s revolutionary Eco-Drive technology harnesses the power of light—from any natural or artificial light source—and converts it into energy, which is stored in a permanently rechargeable power cell.',
    price: 420,
    image: findImage('citizen'),
    isTrending: true,
    brand: 'Citizen',
  },
  {
    id: '58',
    name: 'Citizen Biobío',
    slug: 'citizen-biobio',
    category: 'Japanese',
    description: 'A unique collection inspired by nature.',
    longDescription: 'The Biobío collection from Citizen takes its design inspiration from the natural world, featuring organic shapes and textures. A watch that connects you to the environment.',
    price: 470,
    image: findImage('citizen'),
    isTrending: false,
    brand: 'Citizen',
  },
  {
    id: '59',
    name: 'Citizen Paraclock',
    slug: 'citizen-paraclock',
    category: 'Japanese',
    description: 'Innovative design with a focus on functionality.',
    longDescription: 'The Paraclock collection is a testament to Citizen\'s spirit of innovation, featuring unique functionalities and a modern aesthetic for the tech-savvy individual.',
    price: 490,
    image: findImage('citizen'),
    isTrending: false,
    brand: 'Citizen',
  },
  {
    id: '60',
    name: 'Citizen Skywatch',
    slug: 'citizen-skywatch',
    category: 'Japanese',
    description: 'Pilot watches with advanced features for aviators.',
    longDescription: 'The Skywatch collection is designed for the modern aviator, featuring functions like a pilot\'s slide rule, atomic timekeeping, and world time in multiple cities.',
    price: 550,
    image: findImage('citizen'),
    isTrending: false,
    brand: 'Citizen',
  },

  // Apple
  {
    id: '9',
    name: 'Apple Watch',
    slug: 'apple-watch',
    category: 'Other',
    description: 'The ultimate device for a healthy life.',
    longDescription: 'More than just a timepiece, the Apple Watch is a powerful tool for connectivity, fitness, and health, seamlessly integrated into the Apple ecosystem.',
    price: 799,
    image: findImage('apple'),
    isTrending: true,
    brand: 'Apple',
  },
   {
    id: '61',
    name: 'Apple Watch Nike',
    slug: 'apple-watch-nike',
    category: 'Other',
    description: 'Your perfect running partner.',
    longDescription: 'Apple Watch Nike was made to move with you. With the Nike Run Club app as your ultimate running partner, it\'s the perfect way to stay motivated and connected.',
    price: 810,
    image: findImage('apple'),
    isTrending: false,
    brand: 'Apple',
  },
  {
    id: '62',
    name: 'Apple Watch Hermès',
    slug: 'apple-watch-hermes',
    category: 'Other',
    description: 'Where iconic design meets cutting-edge technology.',
    longDescription: 'A partnership based on parallel thinking and shared values, Apple Watch Hermès is the ultimate tool for modern life, with a sophisticated new collection of watch faces and bands.',
    price: 950,
    image: findImage('apple'),
    isTrending: false,
    brand: 'Apple',
  },
  {
    id: '63',
    name: 'Apple Watch Edition',
    slug: 'apple-watch-edition',
    category: 'Other',
    description: 'Crafted from premium materials like titanium.',
    longDescription: 'The Apple Watch Edition features stunning cases crafted from titanium and ceramic. It represents a new chapter in the story of the watch and a new standard in luxury.',
    price: 900,
    image: findImage('apple'),
    isTrending: false,
    brand: 'Apple',
  },
  {
    id: '64',
    name: 'Apple Watch SE',
    slug: 'apple-watch-se',
    category: 'Other',
    description: 'Heavy on features, light on price.',
    longDescription: 'The Apple Watch SE packs the essential features of Apple Watch into a modern design you love — all at a more affordable price. It\'s a lot of watch for a lot less than you expected.',
    price: 600,
    image: findImage('apple'),
    isTrending: false,
    brand: 'Apple',
  },

];

export const categories: Category[] = [
    {
        name: 'Swiss',
        description: 'Exquisite timepieces from the heart of watchmaking.',
        image: findImage('swiss-category'),
    },
    {
        name: 'Japanese',
        description: 'Cutting-edge technology meets precision craftsmanship.',
        image: findImage('japanese-category'),
    },
    {
        name: 'Other',
        description: 'Modern designs and smart technology for every style.',
        image: findImage('other-category'),
    },
];

export const brands: Brand[] = Array.from(new Set(products.map(p => p.brand)))
    .map(brandName => {
        const product = products.find(p => p.brand === brandName);
        return {
            name: brandName,
            slug: product!.brand.toLowerCase().replace(/ /g, '-').replace(/~/, ''),
            category: product!.category,
        };
    });
