import type { Product, Category, Brand } from './types';
import { PlaceHolderImages } from './placeholder-images';

const findImage = (id: string) => {
  const image = PlaceHolderImages.find((img) => img.id === id);
  if (!image) {
    throw new Error(`Image with id "${id}" not found.`);
  }
  return image;
};

export const products: Product[] = [
  {
    id: '1',
    name: 'Submariner',
    slug: 'rolex-submariner',
    category: 'Swiss',
    description: 'Iconic dive watch, waterproof up to 300m, with a rotating bezel.',
    longDescription: 'The Rolex Submariner is the quintessential divers\' watch, a symbol of underwater exploration. It features a robust and functional design with a unidirectional rotatable bezel and solid-link Oyster bracelet.',
    image: findImage('rolex'),
    isTrending: true,
    brand: 'Rolex',
    modelType: 'Professional',
  },
  {
    id: '2',
    name: 'Omega',
    slug: 'omega',
    category: 'Swiss',
    description: 'A legacy of innovation and deep-sea exploration.',
    longDescription: 'Omega has continually made history, from its role as the official timekeeper for the Olympic Games to being the first watch worn on the moon. Its pioneering spirit is evident in every timepiece.',
    image: findImage('omega'),
    isTrending: false,
    brand: 'Omega',
  },
  {
    id: '3',
    name: 'Patek Philippe',
    slug: 'patek-philippe',
    category: 'Swiss',
    description: 'Unmatched craftsmanship and timeless design.',
    longDescription: 'As the last family-owned independent watch manufacturer in Geneva, Patek Philippe enjoys total creative freedom to entirely design, produce and assemble what experts agree to be the finest timepieces in the world.',
    image: findImage('patek-philippe'),
    isTrending: true,
    brand: 'Patek Philippe',
  },
  {
    id: '4',
    name: 'Tag Heuer',
    slug: 'tag-heuer',
    category: 'Swiss',
    description: 'Avant-garde watchmaking inspired by motorsport.',
    longDescription: 'Since 1860, TAG Heuer has been at the forefront of Swiss watchmaking, pushing boundaries with its relentless pursuit of innovation, high performance, and precision timing.',
    image: findImage('tag-heuer'),
    isTrending: false,
    brand: 'Tag Heuer',
  },
  {
    id: '5',
    name: 'Breitling',
    slug: 'breitling',
    category: 'Swiss',
    description: 'High-performance chronometers for aviation.',
    longDescription: 'Breitling has a global reputation for high-precision timepieces, its pioneering role in the development of the wrist chronograph, and its uncompromising commitment to design excellence.',
    image: findImage('breitling'),
    isTrending: false,
    brand: 'Breitling',
  },
  {
    id: '6',
    name: 'Seiko',
    slug: 'seiko',
    category: 'Japanese',
    description: 'A century of horological innovation.',
    longDescription: 'From the first quartz watch to the revolutionary Spring Drive, Seiko has consistently been a leader in watch technology, offering a wide range of timepieces known for their accuracy and durability.',
    image: findImage('seiko'),
    isTrending: true,
    brand: 'Seiko',
  },
  {
    id: '7',
    name: 'Casio',
    slug: 'casio',
    category: 'Japanese',
    description: 'Durability and technology for everyday life.',
    longDescription: 'Casio is renowned for its G-SHOCK line, which set a new standard for shock-resistant watches. The brand continues to innovate with features that serve a multitude of lifestyles and professions.',
    image: findImage('casio'),
    isTrending: false,
    brand: 'Casio',
  },
  {
    id: '8',
    name: 'Citizen',
    slug: 'citizen',
    category: 'Japanese',
    description: 'Powered by light, for a better future.',
    longDescription: 'Citizen\'s Eco-Drive technology, which harnesses the power of any light source, has revolutionized the watch industry. It represents the brand\'s commitment to innovation and environmental responsibility.',
    image: findImage('citizen'),
    isTrending: true,
    brand: 'Citizen',
  },
  {
    id: '9',
    name: 'Apple Watch',
    slug: 'apple-watch',
    category: 'Other',
    description: 'The ultimate device for a healthy life.',
    longDescription: 'More than just a timepiece, the Apple Watch is a powerful tool for connectivity, fitness, and health. It seamlessly integrates with your digital life, keeping you active, healthy, and connected.',
    image: findImage('apple'),
    isTrending: true,
    brand: 'Apple',
  },
  {
    id: '10',
    name: 'Fossil',
    slug: 'fossil',
    category: 'Other',
    description: 'American creativity and ingenuity.',
    longDescription: 'Fossil offers a modern take on classic design, blending timeless style with contemporary functionality. Its fashion-forward watches and smartwatches are designed to be the perfect accessory for any occasion.',
    image: findImage('fossil'),
    isTrending: false,
    brand: 'Fossil',
  },
  {
    id: '11',
    name: 'Sea-Dweller & Deepsea',
    slug: 'rolex-sea-dweller-deepsea',
    category: 'Swiss',
    description: 'Advanced diving watches with extreme depth resistance.',
    longDescription: 'Rolex\'s ultra-resistant divers\' models engineered for the conquest of the deep. Waterproof to extreme depths, they are the result of decades of collaboration with diving professionals.',
    image: findImage('rolex'),
    isTrending: false,
    brand: 'Rolex',
    modelType: 'Professional',
  },
  {
    id: '12',
    name: 'GMT-Master II',
    slug: 'rolex-gmt-master-ii',
    category: 'Swiss',
    description: 'Dual time-zone watch, popular among pilots and travelers.',
    longDescription: 'Designed to show the time in two different time zones simultaneously, the GMT-Master has been the watch of choice for airline pilots and globetrotters.',
    image: findImage('rolex'),
    isTrending: false,
    brand: 'Rolex',
    modelType: 'Professional',
  },
  {
    id: '13',
    name: 'Cosmograph Daytona',
    slug: 'rolex-cosmograph-daytona',
    category: 'Swiss',
    description: 'Chronograph designed for racing drivers, one of Rolex’s most famous models.',
    longDescription: 'The Cosmograph Daytona is inextricably linked to the world of motor racing. It allows drivers to measure elapsed time and read average speeds on its trademark tachymetric bezel.',
    image: findImage('rolex'),
    isTrending: true,
    brand: 'Rolex',
    modelType: 'Professional',
  },
  {
    id: '14',
    name: 'Explorer & Explorer II',
    slug: 'rolex-explorer',
    category: 'Swiss',
    description: 'Rugged watches built for adventurers and mountaineers.',
    longDescription: 'The Explorer models are designed for optimal legibility even in the dark, a crucial feature for explorers. They are built to withstand the toughest conditions.',
    image: findImage('rolex'),
    isTrending: false,
    brand: 'Rolex',
    modelType: 'Professional',
  },
  {
    id: '15',
    name: 'Air-King',
    slug: 'rolex-air-king',
    category: 'Swiss',
    description: 'Aviation-inspired watch with bold numerals.',
    longDescription: 'The Air-King pays tribute to the pioneers of aviation and the Oyster’s role in the epic story of flight. It features a distinctive black dial with a combination of large 3, 6 and 9 numerals marking the hours.',
    image: findImage('rolex'),
    isTrending: false,
    brand: 'Rolex',
    modelType: 'Professional',
  },
  {
    id: '16',
    name: 'Yacht-Master & Yacht-Master II',
    slug: 'rolex-yacht-master',
    category: 'Swiss',
    description: 'Nautical watches, with regatta timer functionality.',
    longDescription: 'The Yacht-Master is the watch of the open seas. It embodies the spirit of the sailor and is distinguished by its bidirectional rotatable 60-minute graduated bezel.',
    image: findImage('rolex'),
    isTrending: false,
    brand: 'Rolex',
    modelType: 'Professional',
  },
  {
    id: '17',
    name: 'Sky-Dweller',
    slug: 'rolex-sky-dweller',
    category: 'Swiss',
    description: 'Complex model with dual time zones and annual calendar.',
    longDescription: 'An elegant watch for world travellers, the Sky-Dweller features an innovative annual calendar and a dual time zone display, all controlled by its revolutionary Ring Command bezel.',
    image: findImage('rolex'),
    isTrending: false,
    brand: 'Rolex',
    modelType: 'Professional',
  },
  {
    id: '18',
    name: 'Datejust',
    slug: 'rolex-datejust',
    category: 'Swiss',
    description: 'Timeless design with date display, available in many sizes and styles.',
    longDescription: 'The Datejust is the archetype of the classic watch thanks to functions and aesthetics that never go out of style. Launched in 1945, it was the first self-winding waterproof chronometer wristwatch to display the date.',
    image: findImage('rolex'),
    isTrending: true,
    brand: 'Rolex',
    modelType: 'Classic',
  },
  {
    id: '19',
    name: 'Day-Date (President)',
    slug: 'rolex-day-date',
    category: 'Swiss',
    description: 'Luxury watch with day and date spelled out, worn by world leaders.',
    longDescription: 'The Rolex Day-Date, often called the "President," is one of the world\'s most prestigious and recognizable watches. It was the first wristwatch to display the day of the week spelled out in full.',
    image: findImage('rolex'),
    isTrending: true,
    brand: 'Rolex',
    modelType: 'Classic',
  },
  {
    id: '20',
    name: 'Lady-Datejust',
    slug: 'rolex-lady-datejust',
    category: 'Swiss',
    description: 'Elegant version of the Datejust tailored for women.',
    longDescription: 'The Lady-Datejust is a feminine interpretation of the timeless Datejust, featuring a smaller case size and a wide array of dials and precious materials to suit any style.',
    image: findImage('rolex'),
    isTrending: false,
    brand: 'Rolex',
    modelType: 'Classic',
  },
  {
    id: '21',
    name: 'Oyster Perpetual',
    slug: 'rolex-oyster-perpetual',
    category: 'Swiss',
    description: 'Purest Rolex design, simple and versatile.',
    longDescription: 'The Oyster Perpetual is the direct descendant of the original Oyster, the world’s first waterproof wristwatch, on which Rolex has built its reputation since 1926. It is a symbol of universal and classic style.',
    image: findImage('rolex'),
    isTrending: false,
    brand: 'Rolex',
    modelType: 'Classic',
  },
  {
    id: '22',
    name: '1908',
    slug: 'rolex-1908',
    category: 'Swiss',
    description: 'A modern reinterpretation of classic Rolex dress watches.',
    longDescription: 'The Perpetual 1908 is a new, elegant and sober timepiece that celebrates the year Hans Wilsdorf devised the name ‘Rolex’. It brings a modern twist to the classic dress watch.',
    image: findImage('rolex'),
    isTrending: false,
    brand: 'Rolex',
    modelType: 'Classic',
  },
];

export const categories: Category[] = [
    {
        name: 'Swiss',
        description: 'Exquisite timepieces from the heart of watchmaking.',
        image: findImage('swiss-category'),
    },
    {
        name: 'Japanese',
        description: 'Cutting-edge technology meets precision craftsmanship.',
        image: findImage('japanese-category'),
    },
    {
        name: 'Other',
        description: 'Modern designs and smart technology for every style.',
        image: findImage('other-category'),
    },
];

export const brands: Brand[] = Array.from(new Set(products.map(p => p.brand)))
    .map(brandName => {
        const product = products.find(p => p.brand === brandName);
        return {
            name: brandName,
            slug: product!.brand.toLowerCase().replace(/ /g, '-'),
            category: product!.category,
        };
    });
